CREATE TABLE Menu (
    Variable_Firmenname VARCHAR(255),
    Variable_Firmenlogo BLOB,
    Hilfe BLOB,
    Hintergrung BLOB,
    Stundensatz_für_Leistungsphasen DECIMAL(10,2),
    Gut BLOB,
    Neutral BLOB,
    Schlecht BLOB,
    Stundensatz_für_Netto_ProjektWert_in_Projekte DECIMAL(10,2),
    Accountname VARCHAR(255),
    infos VARCHAR(255),
    MwSt DECIMAL(10,2)
);

CREATE TABLE Reg (
    Feedback_Button_JA_NEIN VARCHAR(255)
);

CREATE TABLE Kontakte (
    Abteilung VARCHAR(255),
    Adressblock TEXT,
    Ähnlicher_Firmenschlüssel VARCHAR(255),
    Ähnlicher_Namensschlüssel VARCHAR(255),
    Ähnlichkeit_nach VARCHAR(255),
    ÄhnlichkeitsMultiKey TEXT,
    Ähnlichkeitsschlüssel VARCHAR(255),
    ÄhnlichkeitsTabEtikett TEXT,
    Ähnlichkeitszählung INT,
    Anrede VARCHAR(255),
    Auswahlliste VARCHAR(255),
    Bild BLOB,
    Email_1 VARCHAR(255),
    Email_2 VARCHAR(255),
    EmailAdresse_mit_Name TEXT,
    Erstellt_von VARCHAR(255),
    Fax VARCHAR(255),
    Firma VARCHAR(255),
    Hinweise TEXT,
    Kontaktblock_Firma_Name_Vorname TEXT,
    Kontaktblock_klein TEXT,
    Kontaktblock_Name_Vorname TEXT,
    KontaktID INT,
    Kunde VARCHAR(255),
    Land VARCHAR(255),
    Land_1 VARCHAR(255),
    Land_2 VARCHAR(255),
    Mobil_1 VARCHAR(255),
    Nachname VARCHAR(255),
    Name TEXT,
    Ort_1 VARCHAR(255),
    Ort_2 VARCHAR(255),
    Postfach VARCHAR(255),
    Postleitzahl_1 VARCHAR(255),
    Postleitzahl_2 VARCHAR(255),
    Privat_Mobil VARCHAR(255),
    Privat_Telefon VARCHAR(255),
    Pstatus_ak VARCHAR(255),
    Pstatus_an VARCHAR(255),
    Pstatus_pr VARCHAR(255),
    Straße_1 VARCHAR(255),
    Straße_2 VARCHAR(255),
    Telefon_1 VARCHAR(255),
    Telefonblock TEXT,
    Temp_Daten TEXT,
    test VARCHAR(255),
    Titel VARCHAR(255),
    Typ VARCHAR(255),
    Verantwortlicher VARCHAR(255),
    Vorname VARCHAR(255),
    Vorschau BLOB,
    Webadresse VARCHAR(255)
);

CREATE TABLE Akquise (
    Akquisedetails TEXT,
    Änderungsdatum DATE,
    Deadline DATE,
    Erstellungsdatum DATE,
    Erstellt_von VARCHAR(255),
    KontaktID VARCHAR(255),
    verfolgen VARCHAR(255),
    Verantwortlicher VARCHAR(255),
    AkquiseID VARCHAR(255)
);